services:
  - type: web
    name: inventory-system
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn inventory_system.wsgi:application"
    envVars:
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: True